name: Deploy Pages
on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Inject Secrets into ALL files
        run: |
          find . -type f -not -path '*/.*' -exec sed -i 's/\${FR0ZEN_API_KEY}/${{ secrets.FR0ZEN_API_KEY }}/g' {} +
        env:
          FR0ZEN_API_KEY: ${{ secrets.FR0ZEN_API_KEY }}

      - uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - uses: actions/deploy-pages@v4
